<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evidence" nsURI="http://evidence/1.0" nsPrefix="evidence">
  <eClassifiers xsi:type="ecore:EClass" name="ArtefactModel" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artefact" upperBound="-1"
        eType="#//ArtefactDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoUser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoLocalPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoUsesLocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artefact" eSuperTypes="assuranceasset.ecore#//ManageableAssuranceAsset general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyValue" upperBound="-1"
        eType="#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPart" upperBound="-1"
        eType="#//Artefact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRel" upperBound="-1"
        eType="#//ArtefactRel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLastVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precedentVersion" eType="#//Artefact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConfigurable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyReference" eType="ecore:EClass property.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtefactRel" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modificationEffect" eType="ecore:EEnum general.ecore#//ChangeEffectKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revocationEffect" eType="ecore:EEnum general.ecore#//ChangeEffectKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Artefact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Artefact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtefactDefinition" eSuperTypes="assuranceasset.ecore#//ManageableAssuranceAsset general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artefact" upperBound="-1"
        eType="#//Artefact" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
