<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="process" nsURI="http://process/1.0" nsPrefix="process">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessModel" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivity" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParticipant" upperBound="-1"
        eType="#//Participant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTechnique" upperBound="-1"
        eType="#//Technique" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="assuranceasset.ecore#//ManageableAssuranceAsset general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subActivity" upperBound="-1"
        eType="#//SubActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precedingActivity" upperBound="-1"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" upperBound="-1"
        eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technique" upperBound="-1"
        eType="#//Technique"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRel" upperBound="-1"
        eType="#//ActivityRel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredArtefact" upperBound="-1"
        eType="ecore:EClass evidence.ecore#//Artefact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedArtefact" upperBound="-1"
        eType="ecore:EClass evidence.ecore#//Artefact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetEvent" upperBound="-1"
        eType="ecore:EClass assuranceasset.ecore#//AssuranceAssetEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubActivity" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="general.ecore#//DescribableElement assuranceasset.ecore#//ManageableAssuranceAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedArtefact" upperBound="-1"
        eType="ecore:EClass evidence.ecore#//Artefact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredAssetEvent" upperBound="-1"
        eType="ecore:EClass assuranceasset.ecore#//AssuranceAssetEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Technique" eSuperTypes="assuranceasset.ecore#//AssuranceAsset general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdArtefact" upperBound="-1"
        eType="ecore:EClass evidence.ecore#//Artefact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provenance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" upperBound="-1"
        eType="#//Organization"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="experience" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objective" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integrity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provenance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subOrganization" upperBound="-1"
        eType="#//Organization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accreditation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityRel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum general.ecore#//ActivityRelKind"/>
  </eClassifiers>
</ecore:EPackage>
